(()=>{
const BANK=Array.isArray(window.CUSTOM_QUIZ_BANK)?window.CUSTOM_QUIZ_BANK:[];
const RB_KEY='fom:review-bank:v1',AUTO_FLAG_MISSES=2,MASTERY_TARGET=3;
const $=id=>document.getElementById(id); const letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ';
function rbLoad(){try{const x=JSON.parse(localStorage.getItem(RB_KEY)||'{"items":{}}');if(!x.items)x.items={};return x}catch(e){return {items:{}}}}
function rbSave(x){try{localStorage.setItem(RB_KEY,JSON.stringify(x))}catch(e){}}
function rbId(q){return [q.lecture||'',q.topic||'',q.concept||''].join('||').toLowerCase()}
function rbGet(bank,q){const id=rbId(q);if(!bank.items[id])bank.items[id]={id,lecture:q.lecture||'',topic:q.topic||'',concept:q.concept||'',difficulty:q.difficulty||'',questionStem:q.stem||'',choices:q.options||[],answer:q.answer||'',explanation:q.explanation||'',transferCheck:q.reviewCheck||null,sourceQuiz:(q.sourceQuizzes||[])[0]||'',misses:0,attempts:0,manual:false,active:false,mastered:false,masteryStreak:0,lastConfidence:null,updatedAt:new Date().toISOString()};return bank.items[id]}
function rbOutcome(q,correct,confidence){const b=rbLoad(),e=rbGet(b,q);e.attempts=(e.attempts||0)+1;e.lastConfidence=confidence||null;if(!correct){e.misses=(e.misses||0)+1;e.masteryStreak=0;if(e.mastered||e.misses>=AUTO_FLAG_MISSES)e.active=true;if(e.mastered)e.mastered=false}e.updatedAt=new Date().toISOString();rbSave(b)}
function rbFlag(q){const b=rbLoad(),e=rbGet(b,q);e.manual=true;e.active=true;e.mastered=false;e.masteryStreak=0;e.updatedAt=new Date().toISOString();rbSave(b)}
function rbMastery(q,success){const b=rbLoad(),e=rbGet(b,q);if(success){e.masteryStreak=(e.masteryStreak||0)+1;if(e.masteryStreak>=MASTERY_TARGET){e.active=false;e.mastered=true}}else e.masteryStreak=0;e.updatedAt=new Date().toISOString();rbSave(b)}
function inferWeek(e){let s=[e.lecture,e.sourceQuiz,e.topic].filter(Boolean).join(' ');let m=s.match(/week\s*([2-9])/i);if(m)return 'Week '+m[1];if(/week9/i.test(s))return 'Week 9';return ''}
function reviewPool(){return Object.values(rbLoad().items||{}).filter(e=>e.active).map((e,i)=>({id:'rb'+i,week:inferWeek(e),difficulty:e.difficulty||'Review Bank',lecture:e.lecture||'Review Bank',topic:e.topic||e.concept||'Review Bank',topics:[e.topic,e.concept].filter(Boolean),concept:e.concept||'',stem:e.questionStem,options:e.choices||[],answer:e.answer,explanation:e.explanation||'',reviewCheck:e.transferCheck||null,sourceQuizzes:[e.sourceQuiz||'Review Bank']})).filter(q=>q.stem&&q.options.length&&q.answer)}
const state={mode:'practice',quiz:[],responses:{},advancedResponses:{},confidence:{},advancedConfidence:{},strikes:{},advancedStrikes:{},flags:{},recorded:{},masteryRecorded:{},graded:false,advancedGraded:false,filters:null};
function shuffle(a){const x=a.slice();for(let i=x.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function selectedValues(container){return [...container.querySelectorAll('input[type=checkbox]:checked')].map(x=>x.value)}
function checkedWeeks(){return selectedValues($('weekChecks'))}
function allSource(){return $('source').value==='review'?reviewPool():BANK}
function baseFiltered(){let pool=allSource();const weeks=checkedWeeks(),diff=$('difficulty').value,lect=selectedValues($('lectureOptions')),topics=selectedValues($('topicOptions'));if(weeks.length)pool=pool.filter(q=>!q.week||weeks.includes(q.week));if(diff!=='all')pool=pool.filter(q=>q.difficulty===diff);if(lect.length)pool=pool.filter(q=>lect.includes(q.lecture));if(topics.length)pool=pool.filter(q=>{const ts=[...(q.topics||[]),q.topic].filter(Boolean);return topics.some(t=>ts.includes(t))});const seen=new Set();return pool.filter(q=>{const k=(q.stem||'').replace(/\s+/g,' ').trim().toLowerCase();if(seen.has(k))return false;seen.add(k);return true})}
function refreshFilterOptions(){const pool=allSource();const weeks=checkedWeeks();const diff=$('difficulty').value;const preliminary=pool.filter(q=>(!weeks.length||!q.week||weeks.includes(q.week))&&(diff==='all'||q.difficulty===diff));const oldL=new Set(selectedValues($('lectureOptions'))),oldT=new Set(selectedValues($('topicOptions')));const lectures=[...new Set(preliminary.map(q=>q.lecture).filter(Boolean))].sort();const topics=[...new Set(preliminary.flatMap(q=>[...(q.topics||[]),q.topic]).filter(Boolean))].sort();$('lectureOptions').innerHTML=lectures.map(x=>`<label class="filter-option"><input type="checkbox" value="${escAttr(x)}" ${oldL.has(x)?'checked':''}><span>${esc(x)}</span></label>`).join('');$('topicOptions').innerHTML=topics.map(x=>`<label class="filter-option"><input type="checkbox" value="${escAttr(x)}" ${oldT.has(x)?'checked':''}><span>${esc(x)}</span></label>`).join('');bindOptionChanges();filterList('lecture');filterList('topic');updateEligible()}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function escAttr(s){return esc(s)}
function bindOptionChanges(){document.querySelectorAll('#lectureOptions input,#topicOptions input').forEach(x=>x.addEventListener('change',updateEligible))}
function filterList(kind){const term=$(kind+'Search').value.trim().toLowerCase();document.querySelectorAll('#'+kind+'Options .filter-option').forEach(el=>{el.style.display=el.innerText.toLowerCase().includes(term)?'flex':'none'})}
function updateEligible(){const n=baseFiltered().length;const requested=Math.max(1,Math.min(100,parseInt($('count').value)||20));$('eligibility').innerHTML=`<strong>${n}</strong> unique questions currently match. ${requested>n?`Requested ${requested}; the quiz will use all ${n} available.`:`Ready to draw ${requested} without replacement.`}`;$('activeCount').textContent=reviewPool().length}
function resetResponseState(){state.responses={};state.advancedResponses={};state.confidence={};state.advancedConfidence={};state.strikes={};state.advancedStrikes={};state.flags={};state.recorded={};state.masteryRecorded={};state.graded=false;state.advancedGraded=false}
function buildQuiz(reuseFilters=false){const eligible=baseFiltered();if(!eligible.length){$('eligibility').innerHTML='<strong>0</strong> questions match. Broaden your filters or switch question source.';return}let n=Math.max(1,Math.min(100,parseInt($('count').value)||20,eligible.length));state.quiz=shuffle(eligible).slice(0,n).map((q,i)=>({...q,customNumber:i+1}));resetResponseState();state.mode=$('startMode').value;setMode(state.mode,false);$('builderSection').style.display='none';$('quizWorkspace').style.display='block';renderQuiz();window.scrollTo({top:$('quizWorkspace').offsetTop-10,behavior:'smooth'})}
function viewQ(q){if(state.mode==='advanced'&&q.reviewCheck)return {stem:q.reviewCheck.stem,options:q.reviewCheck.options,answer:q.reviewCheck.answer,explanation:q.reviewCheck.explanation,advanced:true};return {stem:q.stem,options:q.options,answer:q.answer,explanation:q.explanation,advanced:false}}
function respMap(adv){return adv?state.advancedResponses:state.responses}function confMap(adv){return adv?state.advancedConfidence:state.confidence}function strikeMap(adv){return adv?state.advancedStrikes:state.strikes}
function renderQuiz(){const host=$('quiz');host.innerHTML='';state.quiz.forEach(q=>{const v=viewQ(q),adv=v.advanced,key=q.customNumber;const art=document.createElement('article');art.className='question';let tags=[q.week,q.difficulty,q.lecture,q.topic].filter(Boolean);art.innerHTML=`<div class="qtop"><div><div class="qnum">Question ${key}${adv?' · Advanced Review':''}</div><div class="tags">${tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></div><button class="flag ${state.flags[key]?'active':''}" type="button">${state.flags[key]?'Filed for Review':'Flag for Review'}</button></div><div class="stem">${esc(v.stem)}</div><div class="choices"></div><div class="feedback" id="fb-${key}"></div><div class="confidence"><span>Confidence:</span>${['Guessing','Unsure','Confident'].map(x=>`<button class="confidence-btn ${confMap(adv)[key]===x?'active':''}" type="button" data-conf="${x}">${x}</button>`).join('')}</div>`;const ch=art.querySelector('.choices');v.options.forEach((opt,i)=>{const L=letters[i],row=document.createElement('div');row.className='choice-row';const struck=(strikeMap(adv)[key]||[]).includes(L);row.innerHTML=`<button class="choice ${struck?'struck':''}" type="button" data-letter="${L}"><span class="letter">${L}</span><span class="choice-copy">${esc(opt)}</span></button><button class="strike" type="button" title="Strike choice ${L}">S̶</button>`;row.querySelector('.choice').addEventListener('click',()=>choose(q,L));row.querySelector('.strike').addEventListener('click',()=>toggleStrike(q,L));ch.appendChild(row)});art.querySelector('.flag').addEventListener('click',()=>{state.flags[key]=true;rbFlag(q);renderQuiz()});art.querySelectorAll('.confidence-btn').forEach(b=>b.addEventListener('click',()=>{confMap(adv)[key]=b.dataset.conf;paintQuestion(art,q)}));host.appendChild(art);paintQuestion(art,q)});updateProgress()}
function choose(q,L){const v=viewQ(q),adv=v.advanced,key=q.customNumber;respMap(adv)[key]=L;if(!adv&&!state.recorded[key]){state.recorded[key]=true;rbOutcome(q,L===v.answer,confMap(false)[key])}if(adv&&!state.masteryRecorded[key]){state.masteryRecorded[key]=true;rbMastery(q,L===v.answer)}const art=[...document.querySelectorAll('.question')][key-1];paintQuestion(art,q);updateProgress()}
function toggleStrike(q,L){const adv=viewQ(q).advanced,key=q.customNumber,m=strikeMap(adv);m[key]=m[key]||[];m[key]=m[key].includes(L)?m[key].filter(x=>x!==L):[...m[key],L];const art=[...document.querySelectorAll('.question')][key-1];paintQuestion(art,q)}
function shouldShowFeedback(adv){return state.mode==='practice'||(adv?state.advancedGraded:state.graded)||state.mode==='advanced'}
function paintQuestion(art,q){if(!art)return;const v=viewQ(q),adv=v.advanced,key=q.customNumber,r=respMap(adv)[key],show=shouldShowFeedback(adv);art.querySelectorAll('.choice').forEach(btn=>{const L=btn.dataset.letter;btn.classList.toggle('selected',L===r);btn.classList.remove('correct','wrong');const struck=(strikeMap(adv)[key]||[]).includes(L);btn.classList.toggle('struck',struck);if(show&&r){if(L===v.answer)btn.classList.add('correct');else if(L===r)btn.classList.add('wrong')}});art.querySelectorAll('.confidence-btn').forEach(b=>b.classList.toggle('active',confMap(adv)[key]===b.dataset.conf));const fb=art.querySelector('.feedback');if(show&&r){fb.classList.add('show');fb.innerHTML=`<strong>${r===v.answer?'Correct':'Best answer: '+v.answer}</strong><br>${esc(v.explanation)}`}else{fb.classList.remove('show');fb.innerHTML=''}}
function updateProgress(){const adv=state.mode==='advanced',r=respMap(adv),answered=Object.keys(r).length,total=state.quiz.length;let correct=0;state.quiz.forEach(q=>{const v=viewQ(q);if(r[q.customNumber]===v.answer)correct++});$('answeredLabel').textContent=`${answered} of ${total} answered`;$('scoreLabel').textContent=answered?`${adv?'Advanced':'Current'} score: ${correct}/${answered} (${Math.round(correct/answered*100)}%)`:(adv?'Advanced score: —':'Practice score: —');$('progressFill').style.width=(total?answered/total*100:0)+'%'}
function setMode(mode,rerender=true){state.mode=mode;['practice','exam','advanced'].forEach(x=>$(x+'Mode').classList.toggle('active',x===mode));$('modeNote').textContent=mode==='practice'?'Immediate feedback is ON.':mode==='exam'?'Feedback appears after grading.':'Transfer questions test the same concepts in a new way.';if(rerender)renderQuiz()}
function grade(){if(state.mode==='advanced')state.advancedGraded=true;else state.graded=true;renderQuiz();const unanswered=state.quiz.length-Object.keys(respMap(state.mode==='advanced')).length;if(unanswered)$('modeNote').textContent=`Graded with ${unanswered} unanswered question${unanswered===1?'':'s'}.`;else $('modeNote').textContent='Quiz graded.'}
function init(){const weeks=[...new Set(BANK.map(q=>q.week).filter(Boolean))].sort((a,b)=>(parseInt(a.match(/\d+/)?.[0]||99)-parseInt(b.match(/\d+/)?.[0]||99)));$('weekChecks').innerHTML=weeks.map(w=>`<label class="check"><input type="checkbox" value="${escAttr(w)}" checked>${esc(w)}</label>`).join('');$('uniqueCount').textContent=BANK.length;$('bankPill').textContent=`${BANK.length} exact-unique stems · 700 source questions`;document.querySelectorAll('#weekChecks input').forEach(x=>x.addEventListener('change',refreshFilterOptions));$('difficulty').addEventListener('change',refreshFilterOptions);$('source').addEventListener('change',()=>{refreshFilterOptions();updateEligible()});$('count').addEventListener('input',updateEligible);$('lectureSearch').addEventListener('input',()=>filterList('lecture'));$('topicSearch').addEventListener('input',()=>filterList('topic'));$('clearFiltersBtn').addEventListener('click',()=>{document.querySelectorAll('#lectureOptions input,#topicOptions input').forEach(x=>x.checked=false);updateEligible()});$('buildBtn').addEventListener('click',()=>buildQuiz(false));$('practiceMode').addEventListener('click',()=>setMode('practice'));$('examMode').addEventListener('click',()=>setMode('exam'));$('advancedMode').addEventListener('click',()=>setMode('advanced'));$('gradeBtn').addEventListener('click',grade);$('newQuizBtn').addEventListener('click',()=>{$('quizWorkspace').style.display='none';$('builderSection').style.display='grid';window.scrollTo({top:0,behavior:'smooth'});updateEligible()});$('reshuffleBtn').addEventListener('click',()=>buildQuiz(true));refreshFilterOptions();updateEligible()}
init();
})();