import genanki,re,pathlib
C=[
("The basophilic material in a neuronal soma represents {{c1::Nissl substance}}.","Neuron"),
("The organelle responsible for neuronal Nissl staining is {{c1::rough endoplasmic reticulum}}.","Neuron"),
("The relatively pale, Nissl-negative region at the axon's origin is the {{c1::axon hillock}}.","Neuron"),
("An action potential is typically initiated at the {{c1::axon initial segment}}.","Neuron"),
("The fine interwoven mesh of processes and synapses in CNS gray matter is {{c1::neuropil}}.","Neuron"),
("Most somatic motor neurons have {{c1::multipolar}} morphology.","Neuron"),
("The characteristic morphology of dorsal root ganglion primary sensory neurons is {{c1::pseudounipolar}}.","Neuron"),
("A neuron with one dendrite and one axon is {{c1::bipolar}}.","Neuron"),
("Neuronal dendrites primarily {{c1::receive}} signals.","Neuron"),
("A neuron has {{c1::one}} axon in the usual morphologic classification.","Neuron"),
("In peripheral nervous tissue, groups of neuronal cell bodies are called {{c1::ganglia}}.","Organization"),
("In CNS tissue, groups of neuronal cell bodies are called {{c1::nuclei}}.","Organization"),
("Bundles of axons in the PNS are called {{c1::nerves}}.","Organization"),
("Bundles of axons in the CNS are called {{c1::tracts}}.","Organization"),
("The motor-neuron neurotransmitter released at the skeletal neuromuscular junction is {{c1::acetylcholine}}.","Synapses"),
("The enzyme that terminates the acetylcholine signal at the NMJ is {{c1::acetylcholinesterase}}.","Synapses"),
("The specialized postsynaptic skeletal-muscle membrane at the NMJ is the {{c1::motor end plate}}.","Synapses"),
("Fast direct ionic communication between electrically coupled cells occurs through {{c1::gap junctions}}.","Synapses"),
("A motor neuron and all the muscle fibers it innervates constitute one {{c1::motor unit}}.","Synapses"),
("The PNS cell forming compact myelin around a peripheral axon is the {{c1::Schwann cell}}.","Myelin"),
("The CNS cell forming myelin is the {{c1::oligodendrocyte}}.","Myelin"),
("A single Schwann cell forms one {{c1::myelinated internode}} of a peripheral axon.","Myelin"),
("Discontinuities between myelin internodes are called {{c1::nodes of Ranvier}}.","Myelin"),
("Rapid conduction through nodal action-potential regeneration is called {{c1::saltatory conduction}}.","Myelin"),
("Nonmyelinated peripheral axons may still be ensheathed by {{c1::Schwann cells}}.","Myelin"),
("The cellular wrapping that initiates peripheral myelin formation is called a {{c1::mesaxon}}.","Myelin"),
("The connective-tissue sheath around an entire peripheral nerve is the {{c1::epineurium}}.","Sheaths"),
("The sheath around an individual peripheral nerve fascicle is the {{c1::perineurium}}.","Sheaths"),
("The thin connective-tissue covering around individual nerve fibers is the {{c1::endoneurium}}.","Sheaths"),
("A major structural component of the blood–nerve barrier is the {{c1::perineurium}}.","Sheaths"),
("The motor driving anterograde axonal transport is {{c1::kinesin}}.","Transport"),
("The motor driving retrograde axonal transport is {{c1::dynein}}.","Transport"),
("Transport from the soma toward the axon terminal is {{c1::anterograde}}.","Transport"),
("Transport from the axon terminal back to the soma is {{c1::retrograde}}.","Transport"),
("Degeneration of the distal axon after severe injury is {{c1::Wallerian degeneration}}.","Injury"),
("The regenerating axon guidance columns formed by Schwann cells are {{c1::bands of Büngner}}.","Injury"),
("Dispersal of somatic Nissl substance following neuronal injury is {{c1::chromatolysis}}.","Injury"),
("The cells helping clear degenerating peripheral nerve myelin include {{c1::macrophages}}.","Injury"),
("Chronic inherited distal neuropathy with pes cavus is typical of {{c1::Charcot–Marie–Tooth disease}}.","Diseases"),
("Acute postinfectious ascending weakness with areflexia suggests {{c1::Guillain–Barré syndrome}}.","Diseases"),
("The large lower motor neuron somata in spinal cord gray matter reside in the {{c1::anterior horn}}.","SpinalCord"),
("Second-order sensory relay neurons in the spinal cord are associated with the {{c1::posterior horn}}.","SpinalCord"),
("Sympathetic preganglionic neurons in the thoracolumbar cord occur in the {{c1::lateral horn}}.","SpinalCord"),
("The cells lining the spinal central canal are {{c1::ependymal cells}}.","SpinalCord"),
("The outer region of spinal cord consisting primarily of long tracts is {{c1::white matter}}.","SpinalCord"),
("The butterfly-shaped central spinal cord region containing neuronal somata is {{c1::gray matter}}.","SpinalCord"),
("The immune/phagocytic glial cell of the CNS is {{c1::microglia}}.","Glia"),
("The glial cell supporting BBB function and CNS homeostasis is the {{c1::astrocyte}}.","Glia"),
("Neuronal cell bodies in dorsal root ganglia are encircled by {{c1::satellite cells}}.","Ganglia"),
("The sensory ganglion whose neurons typically lack local synapses is the {{c1::dorsal root ganglion}}.","Ganglia"),
("Autonomic ganglia usually contain {{c1::multipolar}} neuron somata.","Ganglia"),
("The enteric neural plexus between intestinal muscle layers is the {{c1::myenteric plexus}}.","Ganglia"),
]
B=[
("What histologic clues distinguish a neuron soma from neighboring glial nuclei?","A neuron has a large euchromatic nucleus, prominent nucleolus, and basophilic Nissl substance; glial nuclei are generally smaller and darker.","Neuron"),
("Why is the axon hillock paler than the adjacent soma on routine staining?","It lacks the Nissl substance (rough ER) characteristic of the neuronal cell body.","Neuron"),
("How can a dorsal root ganglion be distinguished from an autonomic ganglion?","DRG: tightly grouped pseudounipolar neurons with complete satellite-cell cuffs and no local synapses. Autonomic: scattered multipolar somata, incomplete cuffs, and synapses.","Ganglia"),
("Why can a Schwann cell surround several unmyelinated axons but myelinate only one internode?","Unmyelinated axons can occupy multiple pockets of Schwann cytoplasm, whereas compact myelin wraps a single axonal internode.","Myelin"),
("Why are myelin sheaths often pale rings in routine H&E cross-sections?","Much of their lipid content is removed during processing, leaving pale spaces surrounding axonal profiles.","Myelin"),
("What makes saltatory conduction faster than continuous unmyelinated conduction?","Myelin limits current leakage along internodes while action potentials regenerate at nodes of Ranvier.","Myelin"),
("Why does damage to the perineurium threaten nerve function?","Perineurium surrounds fascicles and is part of the blood–nerve barrier, separating their microenvironment from outside tissue.","Sheaths"),
("In a peripheral nerve cross-section, which connective tissue layer should surround a fascicle rather than a single axon?","Perineurium; epineurium surrounds the full nerve and endoneurium surrounds individual fibers.","Sheaths"),
("After axotomy, why can a distal segment degenerate even though the proximal soma survives?","The severed distal axon has lost connection to the cell body needed for maintenance and undergoes Wallerian degeneration.","Injury"),
("How do Schwann cells aid axonal recovery after a peripheral nerve injury?","They help clear myelin and form Bands of Büngner that guide proximal axonal regrowth.","Injury"),
("Why does chromatolysis indicate a neuronal injury response?","Somatic Nissl material disperses as the neuronal cell responds to axonal damage.","Injury"),
("How is axonal degeneration different from demyelinating neuropathy?","Axonal injury involves loss or degeneration of the axon itself; demyelination involves segmental myelin loss with axons potentially initially preserved.","Injury"),
("Why would years of distal weakness and pes cavus favor Charcot–Marie–Tooth over Guillain–Barré?","CMT is a chronic inherited peripheral neuropathy; GBS is typically acute, postinfectious, and associated with ascending weakness and areflexia.","Diseases"),
("Why is rapidly ascending weakness with absent reflexes clinically urgent?","GBS may progress to respiratory muscle weakness and failure.","Diseases"),
("How is a chemical synapse structurally different from an electrical synapse?","Chemical synapses have vesicle-rich presynaptic terminals, a synaptic cleft and postsynaptic receptors; electrical synapses communicate directly through gap junctions.","Synapses"),
("What ends neurotransmitter action at a skeletal neuromuscular junction?","Acetylcholinesterase breaks down acetylcholine in the synaptic cleft.","Synapses"),
("What is the histologic role of the spinal anterior horn?","It contains large lower motor neuron cell bodies responsible for somatic motor output.","SpinalCord"),
("How can you orient a spinal cord section using its motor-neuron populations?","Large lower motor neuron somata identify the anterior/ventral horns.","SpinalCord"),
("Why should a dorsal root ganglion cell body not be mistaken for a second-order dorsal horn neuron?","DRG somata are primary sensory neurons outside the cord; dorsal horn neuronal somata lie within central gray matter and participate in sensory relay.","SpinalCord"),
("Why does the central canal have an epithelial-like lining?","It is lined by ependymal glial cells.","SpinalCord"),
("What distinguishes CNS nuclei from PNS ganglia?","Both contain neuronal cell bodies, but nuclei are located within the CNS and ganglia in the PNS.","Organization"),
("Which direction does dynein move axonal cargo and why is it important?","Retrograde, from terminal toward soma; it returns materials and signals including injury-related information.","Transport"),
("Why does the direction of axonal transport not identify the direction of an action potential?","Cargo movement uses intracellular molecular motors; electrical signaling is a separate process.","Transport"),
("Why do dorsal root ganglion neurons have characteristic complete satellite-cell cuffs?","Their pseudounipolar somata are closely surrounded by peripheral glial satellite cells, yielding a recognizable histologic pattern.","Ganglia"),
]
assert all(x.count('{{c1::')==1 and '{{c2::' not in x for x,_ in C)
out=pathlib.Path('weeks/week13/MSK_Week13_Lecture5_Text_Only_FIXED.apkg')
out.parent.mkdir(parents=True,exist_ok=True)
cloze=genanki.Model(1961105301,'MSK W13 L5 Cloze',fields=[{'name':'Text'},{'name':'Extra'}],templates=[{'name':'Cloze','qfmt':'{{cloze:Text}}','afmt':'{{cloze:Text}}<hr>{{Extra}}'}],model_type=genanki.Model.CLOZE)
basic=genanki.Model(1961105302,'MSK W13 L5 Basic',fields=[{'name':'Front'},{'name':'Back'}],templates=[{'name':'Basic','qfmt':'{{Front}}','afmt':'{{FrontSide}}<hr>{{Back}}'}])
deck=genanki.Deck(1961105399,'MSK · Week 13 · Lecture 5')
for t,tag in C: deck.add_note(genanki.Note(model=cloze,fields=[t,''],tags=[tag]))
for q,a,tag in B: deck.add_note(genanki.Note(model=basic,fields=[q,a],tags=[tag]))
genanki.Package(deck).write_to_file(str(out))
print(f'BUILD COMPLETE: {len(C)} cloze + {len(B)} basic = {len(C)+len(B)} cards, {out}')
