insert into public.quiz_catalog (id,title,module,week,question_count,active) values
('drug-practice-01','Drug Practice Quiz 01','Drug Hub',null,10,true),
('drug-practice-02','Drug Practice Quiz 02','Drug Hub',null,10,true),
('drug-practice-03','Drug Practice Quiz 03','Drug Hub',null,10,true),
('drug-practice-04','Drug Practice Quiz 04','Drug Hub',null,10,true),
('drug-practice-05','Drug Practice Quiz 05','Drug Hub',null,10,true),
('drug-practice-06','Drug Practice Quiz 06','Drug Hub',null,10,true),
('drug-practice-07','Drug Practice Quiz 07','Drug Hub',null,10,true),
('drug-practice-08','Drug Practice Quiz 08','Drug Hub',null,10,true),
('drug-practice-09','Drug Practice Quiz 09','Drug Hub',null,10,true),
('drug-practice-10','Drug Practice Quiz 10','Drug Hub',null,10,true),
('drug-practice-11','Drug Practice Quiz 11','Drug Hub',null,10,true),
('drug-practice-12','Drug Practice Quiz 12','Drug Hub',null,10,true),
('drug-practice-13','Drug Practice Quiz 13','Drug Hub',null,10,true),
('drug-practice-14','Drug Practice Quiz 14','Drug Hub',null,10,true),
('drug-practice-15','Drug Practice Quiz 15','Drug Hub',null,10,true),
('pathology-practice-01','Pathology Practice Quiz 01','Pathology Hub',null,10,true),
('pathology-practice-02','Pathology Practice Quiz 02','Pathology Hub',null,10,true),
('pathology-practice-03','Pathology Practice Quiz 03','Pathology Hub',null,10,true),
('pathology-practice-04','Pathology Practice Quiz 04','Pathology Hub',null,10,true),
('pathology-practice-05','Pathology Practice Quiz 05','Pathology Hub',null,10,true),
('pathology-practice-06','Pathology Practice Quiz 06','Pathology Hub',null,10,true),
('pathology-practice-07','Pathology Practice Quiz 07','Pathology Hub',null,10,true),
('pathology-practice-08','Pathology Practice Quiz 08','Pathology Hub',null,10,true),
('pathology-practice-09','Pathology Practice Quiz 09','Pathology Hub',null,10,true),
('pathology-practice-10','Pathology Practice Quiz 10','Pathology Hub',null,10,true)
on conflict (id) do update set
  title=excluded.title,
  module=excluded.module,
  week=excluded.week,
  question_count=excluded.question_count,
  active=excluded.active;
